// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_dynamodb_all_tables_region": "ap-south-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "test-develop",
            "region": "ap-south-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-south-1:c0908da0-80bc-4c5d-8201-b733dc9dfdcd",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_vPpmoD92V",
    "aws_user_pools_web_client_id": "lttp7cermo6lcfi2l9op02846",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "firstapi",
            "endpoint": "https://9ghaeqpa8j.execute-api.ap-south-1.amazonaws.com/develop",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
