// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:66ffc626-58ed-4e77-9388-ea41c81ec1dd",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_oLFakG34z",
    "aws_user_pools_web_client_id": "2h03b1b89jmkvi5kv9652i2jvj",
    "oauth": {}
};


export default awsmobile;
